//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafePointSecurity {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class VisualWebPart1 {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLinkSafePoint1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLinkSafePoint2;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLinkSafePoint3;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLinkSafePoint4;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLinkSafePoint5;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLinkSafePoint7;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLinkSafePoint8;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLink2;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLink1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLink3;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLink5;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLink4;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ScriptLink ScriptLinkSafePoint10;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(VisualWebPart1 target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLinkSafePoint1() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLinkSafePoint1 = @__ctrl;
            @__ctrl.ID = "ScriptLinkSafePoint1";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/jquery.min.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLinkSafePoint2() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLinkSafePoint2 = @__ctrl;
            @__ctrl.ID = "ScriptLinkSafePoint2";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/bootstrap.min.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLinkSafePoint3() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLinkSafePoint3 = @__ctrl;
            @__ctrl.ID = "ScriptLinkSafePoint3";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/pageRelatorios.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLinkSafePoint4() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLinkSafePoint4 = @__ctrl;
            @__ctrl.ID = "ScriptLinkSafePoint4";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/angular.min.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLinkSafePoint5() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLinkSafePoint5 = @__ctrl;
            @__ctrl.ID = "ScriptLinkSafePoint5";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/angular-filter.min.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLinkSafePoint7() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLinkSafePoint7 = @__ctrl;
            @__ctrl.ID = "ScriptLinkSafePoint7";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/dirPagination.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLinkSafePoint8() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLinkSafePoint8 = @__ctrl;
            @__ctrl.ID = "ScriptLinkSafePoint8";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/underscore-min.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLink2() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLink2 = @__ctrl;
            @__ctrl.ID = "ScriptLink2";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/kjvelarde-multiselect-searchtr" +
                "ee-0.9.5.min.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLink1() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLink1 = @__ctrl;
            @__ctrl.ID = "ScriptLink1";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/kjvelarde-multiselect-searchtr" +
                "ee-0.9.5.tpl.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLink3() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLink3 = @__ctrl;
            @__ctrl.ID = "ScriptLink3";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/loading-bar.min.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLink5() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLink5 = @__ctrl;
            @__ctrl.ID = "ScriptLink5";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/ng-tags-input.min.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLink4() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLink4 = @__ctrl;
            @__ctrl.ID = "ScriptLink4";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/ViewModel/PermissaoViewModel.j" +
                "s";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptLinkSafePoint10() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.ScriptLinkSafePoint10 = @__ctrl;
            @__ctrl.ID = "ScriptLinkSafePoint10";
            @__ctrl.Language = "javascript";
            @__ctrl.Name = "~sitecollection/Style Library/SafePointSecurity/js/safepoint_controller.js";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SafePointSecurity.VisualWebPart1 @__ctrl) {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl1;
            @__ctrl1 = this.@__BuildControlScriptLinkSafePoint1();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl2;
            @__ctrl2 = this.@__BuildControlScriptLinkSafePoint2();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl3;
            @__ctrl3 = this.@__BuildControlScriptLinkSafePoint3();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl4;
            @__ctrl4 = this.@__BuildControlScriptLinkSafePoint4();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl5;
            @__ctrl5 = this.@__BuildControlScriptLinkSafePoint5();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl6;
            @__ctrl6 = this.@__BuildControlScriptLinkSafePoint7();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl7;
            @__ctrl7 = this.@__BuildControlScriptLinkSafePoint8();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl8;
            @__ctrl8 = this.@__BuildControlScriptLink2();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl9;
            @__ctrl9 = this.@__BuildControlScriptLink1();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl10;
            @__ctrl10 = this.@__BuildControlScriptLink3();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl11;
            @__ctrl11 = this.@__BuildControlScriptLink5();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl12;
            @__ctrl12 = this.@__BuildControlScriptLink4();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl13;
            @__ctrl13 = this.@__BuildControlScriptLinkSafePoint10();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<link href=\"/Style%20Library/SafePointSecurity/css/bootstrap.min.css\" rel" +
                        "=\"stylesheet\" />\r\n<link href=\"/Style%20Library/SafePointSecurity/css/icons/simpl" +
                        "e-line-icons.min.css\" rel=\"stylesheet\" />\r\n<link href=\"/Style%20Library/SafePoin" +
                        "tSecurity/css/kjvelarde-multiselect-searchtree-0.9.5.min.css\" rel=\"stylesheet\" /" +
                        ">\r\n<link href=\"/Style%20Library/SafePointSecurity/css/loading-bar.min.css\" rel=\"" +
                        "stylesheet\" />\r\n<link href=\"/Style%20Library/SafePointSecurity/css/ng-tags-input" +
                        ".min.css\" rel=\"stylesheet\" />\r\n<link href=\"/Style%20Library/SafePointSecurity/cs" +
                        "s/default.css\" rel=\"stylesheet\" />\r\n\r\n<div ng-app=\"safepointApp\">\r\n    <div clas" +
                        "s=\"safepoint\" ng-controller=\"safepointController\">\r\n        <div class=\"containe" +
                        "r-fluid\">\r\n            <div id=\"loading-bar-container\"></div>\r\n            <div " +
                        "class=\"navbar-header\">\r\n                <a href=\"#\">\r\n                    <img s" +
                        "rc=\"../Style%20Library/SafePointSecurity/img/logo.png\" alt=\"logo\" style=\"width: " +
                        "102px; margin-right: 40px\" />\r\n                </a>\r\n            </div>\r\n       " +
                        "     <ul class=\"nav nav-tabs\">\r\n                <li class=\"active\">\r\n           " +
                        "         <a data-toggle=\"tab\" href=\"#relatorio\">Relatórios<span></span></a></li>" +
                        "\r\n                <li>\r\n                    <a data-toggle=\"tab\" href=\"#cadastro" +
                        "\">Administração</a></li>\r\n            </ul>\r\n        </div>\r\n\r\n        <div clas" +
                        "s=\"tab-content\">\r\n            <div id=\"relatorio\" class=\"tab-pane fade in active" +
                        "\">\r\n                <div class=\"filtros-bordered\">\r\n                    <div cla" +
                        "ss=\"title\">\r\n                        <div class=\"caption\">\r\n                    " +
                        "        <i class=\" icon-layers font-green\"></i>\r\n                            <sp" +
                        "an class=\"caption-subject font-green bold uppercase\">Relatório</span>\r\n         " +
                        "                   <div class=\"caption-desc font-grey-cascade\">Filtre os itens p" +
                        "ara o relatório.</div>\r\n                        </div>\r\n                    </di" +
                        "v>\r\n                    <div class=\"body\">\r\n                        <div class=\"" +
                        "row\">\r\n                            <div class=\"content-item col-md-3 col-sm-6\">\r" +
                        "\n                                <div class=\"content-item-head list-simple font-" +
                        "white bg-green\">\r\n                                    <div class=\"list-head-titl" +
                        "e-container\">\r\n                                        <div class=\"list-info\">To" +
                        "tal: {{Grupos.length}} itens</div>\r\n                                        <h3 " +
                        "class=\"list-title\">Grupos</h3>\r\n                                    </div>\r\n    " +
                        "                            </div>\r\n                                <div class=\"" +
                        "content-item-container\">\r\n                                    <ul class=\"scrolla" +
                        "ble\">\r\n                                        <li class=\"mt-list-item\" ng-repea" +
                        "t=\"grupo in Grupos\">\r\n                                            <div class=\"li" +
                        "st-icon-container\" ng-class=\"{\'done\': grupo.selecionado}\">\r\n                    " +
                        "                            <i class=\"icon-check\" ng-class=\"{\'icon-check\': grupo" +
                        ".selecionado, \'icon-close\': !grupo.selecionado }\"></i>\r\n                        " +
                        "                    </div>\r\n                                            <div cla" +
                        "ss=\"list-item-content\">\r\n                                                <h3>\r\n " +
                        "                                                   <a href=\"javascript:;\" ng-cli" +
                        "ck=\"Selecionar(grupo, \'grupo\')\">{{grupo.nome}}</a>\r\n                            " +
                        "                    </h3>\r\n                                            </div>\r\n " +
                        "                                       </li>\r\n                                  " +
                        "  </ul>\r\n                                </div>\r\n                            </d" +
                        "iv>\r\n\r\n                            <div class=\"content-item col-md-3 col-sm-6\">\r" +
                        "\n                                <div class=\"content-item-head list-simple font-" +
                        "white bg-blue\">\r\n                                    <div class=\"list-head-title" +
                        "-container\">\r\n                                        <div class=\"list-info\">Tot" +
                        "al: {{Usuarios.length}} itens</div>\r\n                                        <h3" +
                        " class=\"list-title\">Usuários</h3>\r\n                                    </div>\r\n " +
                        "                               </div>\r\n                                <div clas" +
                        "s=\"content-item-container\">\r\n                                    <ul class=\"scro" +
                        "llable\">\r\n                                        <li class=\"mt-list-item\" ng-re" +
                        "peat=\"usuario in Usuarios\">\r\n                                            <div cl" +
                        "ass=\"list-icon-container\" ng-class=\"{\'done\': usuario.selecionado}\">\r\n           " +
                        "                                     <i class=\"icon-check\" ng-class=\"{\'icon-chec" +
                        "k\': usuario.selecionado, \'icon-close\': !usuario.selecionado }\"></i>\r\n           " +
                        "                                 </div>\r\n                                       " +
                        "     <div class=\"list-item-content\">\r\n                                          " +
                        "      <h3>\r\n                                                    <a href=\"javascr" +
                        "ipt:;\" ng-click=\"Selecionar(usuario, \'usuario\')\">{{usuario.nome}}</a>\r\n         " +
                        "                                       </h3>\r\n                                  " +
                        "          </div>\r\n                                        </li>\r\n               " +
                        "                     </ul>\r\n                                </div>\r\n            " +
                        "                </div>\r\n\r\n                            <div class=\"content-item c" +
                        "ol-md-3 col-sm-6\">\r\n                                <div class=\"content-item-hea" +
                        "d list-simple font-white bg-purple\">\r\n                                    <div c" +
                        "lass=\"list-head-title-container\">\r\n                                        <div " +
                        "class=\"list-info\">Total: {{NiveisPermissao.length}} itens</div>\r\n               " +
                        "                         <h3 class=\"list-title\">Permissões</h3>\r\n               " +
                        "                     </div>\r\n                                </div>\r\n           " +
                        "                     <div class=\"content-item-container\">\r\n                     " +
                        "               <ul class=\"scrollable\">\r\n                                        " +
                        "<li class=\"mt-list-item\" ng-repeat=\"nivelPermissao in NiveisPermissao\">\r\n       " +
                        "                                     <div class=\"list-icon-container\" ng-class=\"" +
                        "{\'done\': nivelPermissao.selecionado}\">\r\n                                        " +
                        "        <i class=\"icon-check\" ng-class=\"{\'icon-check\': nivelPermissao.selecionad" +
                        "o, \'icon-close\': !nivelPermissao.selecionado }\"></i>\r\n                          " +
                        "                  </div>\r\n                                            <div class" +
                        "=\"list-item-content\">\r\n                                                <h3>\r\n   " +
                        "                                                 <a href=\"javascript:;\" ng-click" +
                        "=\"Selecionar(nivelPermissao, \'nivelPermissao\')\">{{nivelPermissao.nome}}</a>\r\n   " +
                        "                                             </h3>\r\n                            " +
                        "                </div>\r\n                                        </li>\r\n         " +
                        "                           </ul>\r\n                                </div>\r\n      " +
                        "                      </div>\r\n                            <div class=\"content-it" +
                        "em col-md-3 col-sm-6\">\r\n                                <div class=\"content-item" +
                        "-head list-simple font-white bg-red\">\r\n                                    <div " +
                        "class=\"list-head-title-container\">\r\n                                        <div" +
                        " class=\"list-info\">Total: {{Sites.length}} itens</div>\r\n                        " +
                        "                <h3 class=\"list-title\">Sites</h3>\r\n                             " +
                        "       </div>\r\n                                </div>\r\n                         " +
                        "       <div class=\"content-item-container\">\r\n                                   " +
                        " <ul class=\"scrollable\">\r\n                                        <li class=\"mt-" +
                        "list-item\" ng-repeat=\"site in Sites\">\r\n                                         " +
                        "   <div class=\"list-icon-container\" ng-class=\"{\'done\': site.selecionado}\">\r\n    " +
                        "                                            <i class=\"icon-check\" ng-class=\"{\'ic" +
                        "on-check\': site.selecionado, \'icon-close\': !site.selecionado }\"></i>\r\n          " +
                        "                                  </div>\r\n                                      " +
                        "      <div class=\"list-item-content\">\r\n                                         " +
                        "       <h3>\r\n                                                    <a href=\"javasc" +
                        "ript:;\" ng-click=\"Selecionar(site, \'site\')\">{{site.nome}}</a>\r\n                 " +
                        "                               </h3>\r\n                                          " +
                        "  </div>\r\n                                        </li>\r\n                       " +
                        "             </ul>\r\n                                </div>\r\n                    " +
                        "        </div>\r\n                        </div>\r\n                        <hr />\r\n" +
                        "                        <div class=\"row\">\r\n                            <div clas" +
                        "s=\"table-scrollable report-table-result\">\r\n                                <dir-" +
                        "pagination-controls max-size=\"1000\" boundary-links=\"true\"></dir-pagination-contr" +
                        "ols>\r\n                                <button class=\"btn btn-link\" ng-click=\"exp" +
                        "ortToExcel(\'#table1\')\" ng-hide=\"(!tableResult)\" style=\"float: right; border: 1px" +
                        " solid; border-radius: 5px; text-decoration: none;\">\r\n                          " +
                        "          <span class=\"icon-cloud-download\"></span> Exportar para Excel\r\n       " +
                        "                         </button>\r\n                                <table id=\"t" +
                        "able1\" class=\'table table-striped table-hover\' ng-hide=\"true\">\r\n                " +
                        "                    <thead>\r\n                                        <tr>\r\n     " +
                        "                                       <th>#</th>\r\n                             " +
                        "               <th>Grupo</th>\r\n                                            <th>U" +
                        "suário</th>\r\n                                            <th>Permissão</th>\r\n   " +
                        "                                         <th>Site</th>\r\n                        " +
                        "                </tr>\r\n                                    </thead>\r\n           " +
                        "                         <tbody>\r\n                                        <tr ng" +
                        "-repeat=\'item in tableResult\'>\r\n                                            <td>" +
                        "{{($index + 1)}}</td>\r\n                                            <td>{{item.gr" +
                        "upo.nome}}</td>\r\n                                            <td>{{item.usuario." +
                        "nome}}</td>\r\n                                            <td>{{item.nivelPermiss" +
                        "ao.nome}}</td>\r\n                                            <td><a target=\'_blan" +
                        "k\' href=\"{{\'/\' + item.site.url}}\">{{item.site.nome}}</a></td>\r\n                 " +
                        "                       </tr>\r\n                                    </tbody>\r\n    " +
                        "                            </table>\r\n                                <table cla" +
                        "ss=\"table table-striped table-hover\">\r\n                                    <thea" +
                        "d>\r\n                                        <tr>\r\n                              " +
                        "              <th># </th>\r\n                                            <th ng-cl" +
                        "ick=\"Ordenar(\'grupo.nome\')\">Grupo </th>\r\n                                       " +
                        "     <th ng-click=\"Ordenar(\'usuario.nome\')\">Usuário </th>\r\n                     " +
                        "                       <th ng-click=\"Ordenar(\'permissao.nome\')\">Permissão </th>\r" +
                        "\n                                            <th ng-click=\"Ordenar(\'site.nome\')\"" +
                        ">Site </th>\r\n                                        </tr>\r\n                    " +
                        "                </thead>\r\n                                    <tbody>\r\n         " +
                        "                               <tr dir-paginate=\"item in tableResult | itemsPerP" +
                        "age: pageSize\" current-page=\"currentPage\">\r\n                                    " +
                        "        <td>{{($index + 1) + (currentPage - 1) * pageSize }}</td>\r\n             " +
                        "                               <td>{{item.grupo.nome}}</td>\r\n                   " +
                        "                         <td>{{item.usuario.nome}}</td>\r\n                       " +
                        "                     <td>{{item.nivelPermissao.nome}}</td>\r\n                    " +
                        "                        <td><a target=\"_blank\" href=\"{{\'/\' + item.site.url}}\">{{" +
                        "item.site.nome}}</a></td>\r\n                                        </tr>\r\n      " +
                        "                              </tbody>\r\n                                </table>" +
                        "\r\n                                <dir-pagination-controls max-size=\"10\" boundar" +
                        "y-links=\"true\"></dir-pagination-controls>\r\n                            </div>\r\n " +
                        "                       </div>\r\n                    </div>\r\n                </div" +
                        ">\r\n            </div>\r\n            <div id=\"cadastro\" class=\"tab-pane fade\">\r\n  " +
                        "              <div class=\"filtros-bordered\">\r\n                    <div class=\"ti" +
                        "tle\">\r\n                        <div class=\"caption\">\r\n                          " +
                        "  <i class=\" icon-layers font-green\"></i>\r\n                            <span cla" +
                        "ss=\"caption-subject font-green bold uppercase\">Cadastros</span>\r\n               " +
                        "             <div class=\"caption-desc font-grey-cascade\">Selecione o cadastro qu" +
                        "e deseja gerenciar.</div>\r\n                        </div>\r\n                    <" +
                        "/div>\r\n                    <div class=\"body\">\r\n                        <div clas" +
                        "s=\"row\">\r\n                            <div class=\"panel-group\" id=\"accordion\">\r\n" +
                        "                                <div class=\"panel panel-default\">\r\n             " +
                        "                       <div class=\"panel-heading bg-green\">\r\n                   " +
                        "                     <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#c" +
                        "ollapse1\">\r\n                                            <h4 class=\"panel-title\">" +
                        "Grupos</h4>\r\n                                        </a>\r\n                     " +
                        "               </div>\r\n                                    <div id=\"collapse1\" c" +
                        "lass=\"panel-collapse collapse\">\r\n                                        <div cl" +
                        "ass=\"panel-body\">\r\n                                            <div class=\"row\">" +
                        "\r\n                                                <div class=\"col-md-4\">\r\n      " +
                        "                                              <label style=\"width: 100%\">\r\n     " +
                        "                                                   Grupos:\r\n                    " +
                        "                                    \r\n                                          " +
                        "          </label>\r\n                                                    <ul clas" +
                        "s=\"list-group\" style=\"max-height: 300px; overflow: auto\">\r\n                     " +
                        "                                   <li class=\"list-group-item\" ng-repeat=\"grupo " +
                        "in Grupos\">\r\n                                                            <a href" +
                        "=\"javascript:;\" ng-click=\"PrencheMembros(grupo)\">{{grupo.nome}} </a>\r\n          " +
                        "                                                  <span class=\"badge\" ng-show=\"g" +
                        "rupo.usuarios && grupo.usuarios.length > 0\">{{grupo.usuarios.length}} \r\n        " +
                        "                                                        <i class=\" icon-users\"><" +
                        "/i>\r\n                                                            </span>\r\n      " +
                        "                                                  </li>\r\n                       " +
                        "                             </ul>\r\n                                            " +
                        "    </div>\r\n                                                <div class=\"col-md-8" +
                        "\">\r\n                                                    <label style=\"width: 100" +
                        "%\">\r\n                                                        Membros{{\' de \' + g" +
                        "rupoSelecionadoAdmin.nome}}:\r\n                                                  " +
                        "      <a href=\"#\" ng-click=\"OpenUrlAddUser(grupoSelecionadoAdmin)\" ng-show=\"grup" +
                        "oSelecionadoAdmin != false\">\r\n                                                  " +
                        "          <span class=\"badge pull-right bg-greenligth\">\r\n                       " +
                        "                                         <i class=\" icon-plus\" style=\"font-size:" +
                        " 20px\"></i>\r\n                                                                Adi" +
                        "cionar\r\n                                                            </span>\r\n   " +
                        "                                                     </a>\r\n                     " +
                        "                               </label>\r\n                                       " +
                        "             <ul class=\"list-group\" style=\"max-height: 300px; overflow: auto\">\r\n" +
                        "                                                        <li class=\"list-group-it" +
                        "em\" ng-repeat=\"usuario in MembrosGrupo\">\r\n                                      " +
                        "                      <a href=\"javascript:;\">{{usuario.nome}} </a>\r\n            " +
                        "                                                <span class=\"badge bg-red\" ng-cl" +
                        "ick=\"$parent.RemoverUsuario(usuario, $parent.grupoSelecionadoAdmin)\">\r\n         " +
                        "                                                       <i class=\" icon-user-unfo" +
                        "llow\" style=\"font-size: 16px\"></i>\r\n                                            " +
                        "                </span>\r\n\r\n                                                     " +
                        "   </li>\r\n                                                    </ul>\r\n           " +
                        "                                     </div>\r\n                                   " +
                        "         </div>\r\n                                        </div>\r\n               " +
                        "                     </div>\r\n                                </div>\r\n\r\n         " +
                        "                       <div class=\"panel panel-default\">\r\n                      " +
                        "              <div class=\"panel-heading bg-blue\">\r\n                             " +
                        "           <h4 class=\"panel-title\">\r\n                                           " +
                        " <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse2\">\r\n        " +
                        "                                        <h4 class=\"panel-title\">Permissões</h4>\r" +
                        "\n                                            </a>\r\n                             " +
                        "           </h4>\r\n                                    </div>\r\n                  " +
                        "                  <div id=\"collapse2\" class=\"panel-collapse collapse\">\r\n        " +
                        "                                <div class=\"panel-body\">\r\n\r\n                    " +
                        "                        <div class=\"row\">\r\n                                     " +
                        "           <div class=\"col-md-4\">\r\n                                             " +
                        "       <label style=\"width: 100%\">Sites:</label>\r\n                              " +
                        "                      <multiselect-searchtree\r\n                                 " +
                        "                       multi-select=\"false\"\r\n                                   " +
                        "                     data-input-model=\"treeview\"\r\n                              " +
                        "                          data-output-model=\"siteSelecionadoAdmin\"\r\n            " +
                        "                                            data-callback=\"SelecionarSite(item, " +
                        "selectedItems)\"\r\n                                                        data-se" +
                        "lect-only-leafs=\"false\">\r\n                                                    </" +
                        "multiselect-searchtree>\r\n                                                </div>\r" +
                        "\n                                                <div class=\"col-md-8\">\r\n       " +
                        "                                             <label style=\"width: 100%\">\r\n      " +
                        "                                                  Permissões{{\' de \' + siteSelec" +
                        "ionadoAdmin.nome}}:\r\n                                                        <a " +
                        "href=\"#\" ng-show=\"siteSelecionadoAdmin != false\" data-toggle=\"modal\" data-target" +
                        "=\"#myModal\" class=\"pull-right\">\r\n                                               " +
                        "             <span class=\"badge pull-right bg-greenligth\">\r\n                    " +
                        "                                            <i class=\" icon-plus\" style=\"font-si" +
                        "ze: 20px\"></i>\r\n                                                                " +
                        "Adicionar\r\n                                                            </span>\r\n" +
                        "                                                        </a>\r\n                  " +
                        "                                  </label>\r\n                                    " +
                        "                <ul class=\"list-group\" style=\"max-height: 300px; overflow: auto\"" +
                        ">\r\n                                                        <li class=\"list-group" +
                        "-item\" ng-repeat=\"item in SitePermissoes\">\r\n                                    " +
                        "                        <a href=\"javascript:;\">{{item.nome}} - {{item.permissao}" +
                        "} </a>\r\n                                                            <span class=" +
                        "\"badge bg-red\" ng-click=\"$parent.RemoverPermissao(item, $parent.siteSelecionadoA" +
                        "dmin)\">\r\n                                                                <i clas" +
                        "s=\" icon-user-unfollow\" style=\"font-size: 16px\"></i>\r\n                          " +
                        "                                  </span>\r\n\r\n                                   " +
                        "                     </li>\r\n                                                    " +
                        "</ul>\r\n                                                </div>\r\n                 " +
                        "                           </div>\r\n                                        </div" +
                        ">\r\n                                    </div>\r\n                                <" +
                        "/div>\r\n                            </div>\r\n                        </div>\r\n     " +
                        "               </div>\r\n                </div>\r\n            </div>\r\n        </div" +
                        ">\r\n        <!-- Modal -->\r\n        <div class=\"modal fade\" id=\"myModal\" tabindex" +
                        "=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">\r\n            <div class=\"mod" +
                        "al-dialog\" role=\"document\">\r\n                <div class=\"modal-content\">\r\n      " +
                        "              <div class=\"modal-header\">\r\n                        <button type=\"" +
                        "button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=" +
                        "\"true\">&times;</span></button>\r\n                        <h4 class=\"modal-title\" " +
                        "id=\"myModalLabel\">Adicionar Permissão</h4>\r\n                    </div>\r\n        " +
                        "            <div class=\"modal-body\">\r\n                        <div class=\"modal-" +
                        "body\">\r\n\r\n                            <div class=\"row\">\r\n                       " +
                        "         <div class=\"col-md-12\">\r\n                                    <label for" +
                        "=\"novoValor\">Grupo:</label>\r\n                                    \r\n             " +
                        "                       <input type=\"text\" ng-model=\"permissao.nome\" class=\"form-" +
                        "control\" placeholder=\"Informe o nome do grupo\" />\r\n                             " +
                        "   </div>\r\n                            </div>\r\n                            <hr /" +
                        ">\r\n                            <div class=\"row\">\r\n                              " +
                        "  <div class=\"col-md-12\">\r\n                                    <label for=\"novoV" +
                        "alor2\">Permissão:</label>\r\n                                    <div class=\"radio" +
                        "\" ng-repeat=\"item in NiveisPermissaoAdm\">\r\n                                     " +
                        "   <label>\r\n                                            <input type=\"radio\" name" +
                        "=\"optradio\" ng-model=\"$parent.permissao.nivelPermissao\" ng-value=\"item.nome\" />{" +
                        "{item.nome}}</label>\r\n                                    </div>\r\n              " +
                        "                  </div>\r\n                            </div>\r\n\r\n                " +
                        "        </div>\r\n                    </div>\r\n                    <div class=\"moda" +
                        "l-footer\">\r\n                        <button type=\"button\" class=\"btn btn-default" +
                        "\" data-dismiss=\"modal\">Fechar</button>\r\n                        <button id=\"btAt" +
                        "ualizarValor\" type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" ng-clic" +
                        "k=\"AdicionarPermissao()\">Salvar</button>\r\n                    </div>\r\n          " +
                        "      </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
